package com.loa.system.oasystem.dao.expense;

import com.loa.system.oasystem.entity.expense.GenExpense;
import com.loa.system.oasystem.entity.expense.GenExpenseExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface GenExpenseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    long countByExample(GenExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    int deleteByExample(GenExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short expid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    int insert(GenExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    int insertSelective(GenExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    GenExpense selectOneByExample(GenExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    GenExpense selectOneByExampleSelective(@Param("example") GenExpenseExample example, @Param("selective") GenExpense.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    List<GenExpense> selectByExampleSelective(@Param("example") GenExpenseExample example, @Param("selective") GenExpense.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    List<GenExpense> selectByExample(GenExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    GenExpense selectByPrimaryKeySelective(@Param("expid") Short expid, @Param("selective") GenExpense.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    GenExpense selectByPrimaryKey(Short expid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    GenExpense selectByPrimaryKeyWithLogicalDelete(@Param("expid") Short expid, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenExpense record, @Param("example") GenExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenExpense record, @Param("example") GenExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenExpense record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GenExpenseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expense
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Short expid);
}