package com.loa.system.oasystem.dao.payment;

import com.loa.system.oasystem.entity.payment.GenPayment;
import com.loa.system.oasystem.entity.payment.GenPaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface GenPaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    long countByExample(GenPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int deleteByExample(GenPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int insert(GenPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int insertSelective(GenPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    GenPayment selectOneByExample(GenPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    GenPayment selectOneByExampleSelective(@Param("example") GenPaymentExample example, @Param("selective") GenPayment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    List<GenPayment> selectByExampleSelective(@Param("example") GenPaymentExample example, @Param("selective") GenPayment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    List<GenPayment> selectByExample(GenPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    GenPayment selectByPrimaryKeySelective(@Param("pid") Short pid, @Param("selective") GenPayment.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    GenPayment selectByPrimaryKey(Short pid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    GenPayment selectByPrimaryKeyWithLogicalDelete(@Param("pid") Short pid, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenPayment record, @Param("example") GenPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenPayment record, @Param("example") GenPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenPayment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GenPaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Short pid);
}