package com.loa.system.oasystem.dao.rolePermission;

import com.loa.system.oasystem.entity.rolePermission.GenAdminRolePermissionExample;
import com.loa.system.oasystem.entity.rolePermission.GenAdminRolePermissionKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface GenAdminRolePermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    long countByExample(GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int deleteByExample(GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GenAdminRolePermissionKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int insert(GenAdminRolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int insertSelective(GenAdminRolePermissionKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    GenAdminRolePermissionKey selectOneByExample(GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    GenAdminRolePermissionKey selectOneByExampleSelective(@Param("example") GenAdminRolePermissionExample example, @Param("selective") GenAdminRolePermissionKey.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    List<GenAdminRolePermissionKey> selectByExampleSelective(@Param("example") GenAdminRolePermissionExample example, @Param("selective") GenAdminRolePermissionKey.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    List<GenAdminRolePermissionKey> selectByExample(GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenAdminRolePermissionKey record, @Param("example") GenAdminRolePermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_permission
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenAdminRolePermissionKey record, @Param("example") GenAdminRolePermissionExample example);
}