package com.loa.system.oasystem.dao.expimage;

import com.loa.system.oasystem.entity.expimage.GenExpimage;
import com.loa.system.oasystem.entity.expimage.GenExpimageExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface GenExpimageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    long countByExample(GenExpimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    int deleteByExample(GenExpimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short imgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    int insert(GenExpimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    int insertSelective(GenExpimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    GenExpimage selectOneByExample(GenExpimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    GenExpimage selectOneByExampleSelective(@Param("example") GenExpimageExample example, @Param("selective") GenExpimage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    List<GenExpimage> selectByExampleSelective(@Param("example") GenExpimageExample example, @Param("selective") GenExpimage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    List<GenExpimage> selectByExample(GenExpimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    GenExpimage selectByPrimaryKeySelective(@Param("imgid") Short imgid, @Param("selective") GenExpimage.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    GenExpimage selectByPrimaryKey(Short imgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    GenExpimage selectByPrimaryKeyWithLogicalDelete(@Param("imgid") Short imgid, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenExpimage record, @Param("example") GenExpimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenExpimage record, @Param("example") GenExpimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenExpimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenExpimage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GenExpimageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expimage
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Short imgid);
}