package com.loa.system.oasystem.dao.employee;

import com.loa.system.oasystem.entity.employee.GenEmployee;
import com.loa.system.oasystem.entity.employee.GenEmployeeExample;
import com.loa.system.oasystem.vo.EmployeeVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

@Repository
@Mapper
public interface GenEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    long countByExample(GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int deleteByExample(GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short empid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int insert(GenEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int insertSelective(GenEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    GenEmployee selectOneByExample(GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    GenEmployee selectOneByExampleSelective(@Param("example") GenEmployeeExample example, @Param("selective") GenEmployee.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    List<GenEmployee> selectByExampleSelective(@Param("example") GenEmployeeExample example, @Param("selective") GenEmployee.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    List<GenEmployee> selectByExample(GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    GenEmployee selectByPrimaryKeySelective(@Param("empid") Short empid, @Param("selective") GenEmployee.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    GenEmployee selectByPrimaryKey(Short empid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    GenEmployee selectByPrimaryKeyWithLogicalDelete(@Param("empid") Short empid, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenEmployee record, @Param("example") GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenEmployee record, @Param("example") GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Short empid);

    /**
     * 模糊查询名字
     * @param ename
     * @return
     */
    List<String> findByLeaderNameLike(String ename);

    /**
     *
     * @param ename 用户名字
     * @param deptno  部门编号
     * @param onduty  是否在职
     * @param hiredate 入职时间
     * @return
     */
    List<EmployeeVo> findByEmployeeList(@Param("ename") String ename,
                                        @Param("deptno") Short deptno,
                                        @Param("onduty") Short onduty,
                                        @Param("hiredate") LocalDateTime hiredate);
}