package com.loa.system.oasystem.dao.employee;

import com.loa.system.oasystem.entity.employee.GenEmployee;
import com.loa.system.oasystem.entity.employee.GenEmployeeExample;
import com.loa.system.oasystem.vo.EmployeeVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

@Repository
@Mapper
public interface GenEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    long countByExample(GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int deleteByExample(GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short empid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int insert(GenEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int insertSelective(GenEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    GenEmployee selectOneByExample(GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    GenEmployee selectOneByExampleSelective(@Param("example") GenEmployeeExample example, @Param("selective") GenEmployee.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    List<GenEmployee> selectByExampleSelective(@Param("example") GenEmployeeExample example, @Param("selective") GenEmployee.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    List<GenEmployee> selectByExample(GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    GenEmployee selectByPrimaryKeySelective(@Param("empid") Short empid, @Param("selective") GenEmployee.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    GenEmployee selectByPrimaryKey(Short empid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    GenEmployee selectByPrimaryKeyWithLogicalDelete(@Param("empid") Short empid, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenEmployee record, @Param("example") GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenEmployee record, @Param("example") GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GenEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Short empid);

    /**
     * 模糊查询领导名字
     * @param ename
     * @return
     */
    List<String> findByLeaderNameLike(String ename);

    /**
     * 查询员工列表
     * @param ename
     * @param deptno
     * @param onduty
     * @param localDateTime
     * @return
     */
    List<EmployeeVo> findByEmployeeList(String ename, Short deptno, Short onduty, LocalDateTime localDateTime);

    /**
     * 重置员工密码
     * @param empid
     * @param password
     * @return
     */
    Integer updatePassword(@Param("empid") Short empid ,@Param("password") String password);
}