package com.loa.system.oasystem.dao.duty;

import com.loa.system.oasystem.entity.duty.GenDuty;
import com.loa.system.oasystem.entity.duty.GenDutyExample;
import com.loa.system.oasystem.vo.DutyVo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

@Repository
@Mapper
public interface GenDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    long countByExample(GenDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int deleteByExample(GenDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short dtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int insert(GenDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int insertSelective(GenDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    GenDuty selectOneByExample(GenDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    GenDuty selectOneByExampleSelective(@Param("example") GenDutyExample example, @Param("selective") GenDuty.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    List<GenDuty> selectByExampleSelective(@Param("example") GenDutyExample example, @Param("selective") GenDuty.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    List<GenDuty> selectByExample(GenDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    GenDuty selectByPrimaryKeySelective(@Param("dtid") Short dtid, @Param("selective") GenDuty.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    GenDuty selectByPrimaryKey(Short dtid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenDuty record, @Param("example") GenDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenDuty record, @Param("example") GenDutyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenDuty record);

    /**
     * 查询员工考勤列表
     * @param ename
     * @param deptname
     * @param localDateTime
     * @return
     */
    List<DutyVo> findByDutyList(@Param("dtid") Short dtid,
                                @Param("ename") String ename,
                                @Param("deptname") String deptname,
                                @Param("localDateTime") LocalDateTime localDateTime);

}