package com.loa.system.oasystem.dao.userRole;

import com.loa.system.oasystem.entity.userRole.GenAdminUserRoleExample;
import com.loa.system.oasystem.entity.userRole.GenAdminUserRoleKey;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface GenAdminUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    long countByExample(GenAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    int deleteByExample(GenAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(GenAdminUserRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    int insert(GenAdminUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    int insertSelective(GenAdminUserRoleKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    GenAdminUserRoleKey selectOneByExample(GenAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    GenAdminUserRoleKey selectOneByExampleSelective(@Param("example") GenAdminUserRoleExample example, @Param("selective") GenAdminUserRoleKey.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    List<GenAdminUserRoleKey> selectByExampleSelective(@Param("example") GenAdminUserRoleExample example, @Param("selective") GenAdminUserRoleKey.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    List<GenAdminUserRoleKey> selectByExample(GenAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenAdminUserRoleKey record, @Param("example") GenAdminUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenAdminUserRoleKey record, @Param("example") GenAdminUserRoleExample example);
}