package com.loa.system.oasystem.dao.auditing;

import com.loa.system.oasystem.entity.auditing.GenAuditing;
import com.loa.system.oasystem.entity.auditing.GenAuditingExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface GenAuditingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    long countByExample(GenAuditingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    int deleteByExample(GenAuditingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short auditid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    int insert(GenAuditing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    int insertSelective(GenAuditing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    GenAuditing selectOneByExample(GenAuditingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    GenAuditing selectOneByExampleSelective(@Param("example") GenAuditingExample example, @Param("selective") GenAuditing.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    List<GenAuditing> selectByExampleSelective(@Param("example") GenAuditingExample example, @Param("selective") GenAuditing.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    List<GenAuditing> selectByExample(GenAuditingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    GenAuditing selectByPrimaryKeySelective(@Param("auditid") Short auditid, @Param("selective") GenAuditing.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    GenAuditing selectByPrimaryKey(Short auditid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    GenAuditing selectByPrimaryKeyWithLogicalDelete(@Param("auditid") Short auditid, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenAuditing record, @Param("example") GenAuditingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenAuditing record, @Param("example") GenAuditingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenAuditing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenAuditing record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GenAuditingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auditing
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Short auditid);
}