package com.loa.system.oasystem.dao.income;

import com.loa.system.oasystem.entity.income.GenIncome;
import com.loa.system.oasystem.entity.income.GenIncomeExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface GenIncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    long countByExample(GenIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    int deleteByExample(GenIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short icid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    int insert(GenIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    int insertSelective(GenIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    GenIncome selectOneByExample(GenIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    GenIncome selectOneByExampleSelective(@Param("example") GenIncomeExample example, @Param("selective") GenIncome.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    List<GenIncome> selectByExampleSelective(@Param("example") GenIncomeExample example, @Param("selective") GenIncome.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    List<GenIncome> selectByExample(GenIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    GenIncome selectByPrimaryKeySelective(@Param("icid") Short icid, @Param("selective") GenIncome.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    GenIncome selectByPrimaryKey(Short icid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    GenIncome selectByPrimaryKeyWithLogicalDelete(@Param("icid") Short icid, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenIncome record, @Param("example") GenIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenIncome record, @Param("example") GenIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GenIncomeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table income
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Short icid);
}