package com.loa.system.oasystem.dao.expenseitem;

import com.loa.system.oasystem.entity.expenseitem.GenExpenseitem;
import com.loa.system.oasystem.entity.expenseitem.GenExpenseitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
@Mapper
public interface GenExpenseitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    long countByExample(GenExpenseitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    int deleteByExample(GenExpenseitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    int insert(GenExpenseitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    int insertSelective(GenExpenseitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    GenExpenseitem selectOneByExample(GenExpenseitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    GenExpenseitem selectOneByExampleSelective(@Param("example") GenExpenseitemExample example, @Param("selective") GenExpenseitem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    List<GenExpenseitem> selectByExampleSelective(@Param("example") GenExpenseitemExample example, @Param("selective") GenExpenseitem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    List<GenExpenseitem> selectByExample(GenExpenseitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    GenExpenseitem selectByPrimaryKeySelective(@Param("itemid") Short itemid, @Param("selective") GenExpenseitem.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    GenExpenseitem selectByPrimaryKey(Short itemid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    GenExpenseitem selectByPrimaryKeyWithLogicalDelete(@Param("itemid") Short itemid, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GenExpenseitem record, @Param("example") GenExpenseitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GenExpenseitem record, @Param("example") GenExpenseitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GenExpenseitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GenExpenseitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") GenExpenseitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table expenseitem
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Short itemid);
}